### ISSUE TITLE
version mismatch error in trying to run with gridster2

### ISSUE THREAD

**Issue by viksakshum** [tiberiuzuld/angular-gridster2#306]
i installed it and when i run it i am hittin

ERROR in Error: Metadata version mismatch for module /Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/angular-gridster2/dist/index.d.ts, found version 4, expected 3, resolving symbol AppModule in fa-app/fa-apps/src/app/app.module.ts, resolving symbol AppModule in fa-app/fa-apps/src/app/app.module.ts
    at Error (native)
    at syntaxError (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/vskumar/Dropbox/OscIbcsBotsGit/angular-material/fa-app/fa-apps/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by viksakshum** [comment]
my package.json
{
  "name": "fa-apps",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-gridster2": "^5.2.1",
    "angular2-google-chart": "^2.3.0",
    "chart.js": "^2.7.1",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "ng2-charts": "^1.6.0",
    "ng2-dragula": "^1.5.0",
    "rxjs": "^5.4.2",
    "slick-carousel": "^1.8.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.9",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.16",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}

**Comment by tiberiuzuld** [comment]
Hi @viksakshum ,
You need angular 5 to use last version of library.
For angular 4 the last version of library is 3.19.0

**Comment by viksakshum** [comment]
thanks upgrading everying to angular 5 made it work
