### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dzhavat** [tiberiuzuld/angular-gridster2#60]
Hi, I was playing with gridster and found another “Maximum call stack size exceeded” type of issue.

Here's a gif that illustrates the problem.

![problem](https://user-images.githubusercontent.com/1096332/27073957-e8d4ece2-5025-11e7-9866-81f43a11f04d.gif)

The only thing I've changed is some code in the `ngOnInit` hook. 

Here's my version:

```
ngOnInit() {
    this.options = {
      gridType: 'fixed',
      compactUp: true,
      compactLeft: false,
      itemChangeCallback: AppComponent.itemChange,
      itemResizeCallback: AppComponent.itemResize,
      margin: 10,
      outerMargin: true,
      minCols: 1,
      maxCols: 15,
      minRows: 1,
      maxRows: 100,
      maxItemCols: 5,
      minItemCols: 1,
      maxItemRows: 50,
      minItemRows: 1,
      defaultItemCols: 1,
      defaultItemRows: 1,
      fixedColWidth: 100,
      fixedRowHeight: 100,
      draggable: {
        enabled: true,
        stop: AppComponent.eventStop
      },
      resizable: {
        enabled: true,
        stop: AppComponent.eventStop
      },
      swap: false,
      pushItems: true,
      displayGrid: 'always'
    };

    this.dashboard = [
      {cols: 1, rows: 1, y: 0, x: 14},
      {cols: 2, rows: 1, y: 1, x: 13}
    ];
  }
```

Edit: Here I'm using v.2.10.5

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
Will investigate this week.

Thanks,

**Comment by AxxlForce** [comment]
i got a similar error

[ERROR] /angularErrorHandler 
Error:  Maximum call stack size exceeded 
Stack:  RangeError: Maximum call stack size exceeded
    at GridsterComponent.webpackJsonp../node_modules/angular-gridster2/dist/gridster.component.js.GridsterComponent.checkCollision (http://localhost:4200/0.chunk.js:213:59)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.push (http://localhost:4200/0.chunk.js:935:51)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.tryEast (http://localhost:4200/0.chunk.js:1003:18)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.push (http://localhost:4200/0.chunk.js:957:26)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.tryNorth (http://localhost:4200/0.chunk.js:991:18)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.push (http://localhost:4200/0.chunk.js:948:26)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.tryEast (http://localhost:4200/0.chunk.js:1003:18)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.push (http://localhost:4200/0.chunk.js:951:31)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.tryEast (http://localhost:4200/0.chunk.js:1003:18)
    at GridsterPush.webpackJsonp../node_modules/angular-gridster2/dist/gridsterPush.service.js.GridsterPush.push (http://localhost:4200/0.chunk.js:951:31)

**Comment by tiberiuzuld** [comment]
Hi guys,
Made a fix in v2.10.6.
Let me know if you see any more issues.

Thanks,

**Comment by dzhavat** [comment]
Seems to be working great!
Good job 👍

**Comment by tiberiuzuld** [comment]
Great!
