### ISSUE TITLE
Resizing in Angular causing this

### ISSUE THREAD

**Issue by ksrao** [tiberiuzuld/angular-gridster2#891]
core.mjs:10194  ERROR TypeError: Cannot read properties of null (reading 'renderer')
    at angular-gridster2.mjs:2761:35
    at timer (zone.js:2355:41)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25998:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25998:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:26308:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at invokeTask (zone.js:483:34)

**Comment by ksrao** [comment]
Please ignore it was my mistake. I was resetting widget or destroying it when I resized

**Comment by ksrao** [comment]
Please ignore it was my mistake. I was resetting widget or destroying it when I resized
